_IGNORE := '\s'
Num := '(\+|\-)?[1-9][0-9]*'

%%%

$ := <Exp>

<Exp> := Num : [1]
    := <Exp> '+' <Exp> : [2]
    := <Exp> '*' <Exp> : [3]
    := <Exp> '/' <Exp> : [4]
    := <Exp> '-' <Exp> : [5]
    := '(' <Exp> ')' : [6]

%%%

('*' '/') ('+' '-')
